DEFAULT_MODEL_PROVIDERS = [
    {
        "id": "openai",
        "name": "OpenAI",
        "model_types": ["llm", "image"],
        "base_url": "https://api.openai.com/v1",
        "recommended_models": ["gpt-4.1", "gpt-4.1-mini", "gpt-image-1"],
    },
    {
        "id": "deepseek",
        "name": "DeepSeek",
        "model_types": ["llm"],
        "base_url": "https://api.deepseek.com",
        "recommended_models": ["deepseek-chat", "deepseek-reasoner"],
    },
    {
        "id": "anthropic",
        "name": "Anthropic",
        "model_types": ["llm"],
        "base_url": "https://api.anthropic.com",
        "recommended_models": ["claude-3-5-sonnet-latest"],
    },
    {
        "id": "qwen",
        "name": "通义千问",
        "model_types": ["llm"],
        "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
        "recommended_models": ["qwen-plus", "qwen-max", "qwen-turbo"],
    },
    {
        "id": "volcengine",
        "name": "火山方舟",
        "model_types": ["llm", "image"],
        "base_url": "https://ark.cn-beijing.volces.com/api/v3",
        "recommended_models": ["doubao-pro", "doubao-lite", "jimeng-image"],
    },
    {
        "id": "siliconflow",
        "name": "硅基流动",
        "model_types": ["llm", "image"],
        "base_url": "https://api.siliconflow.cn/v1",
        "recommended_models": ["Qwen/Qwen3-32B", "deepseek-ai/DeepSeek-V3"],
    },
    {
        "id": "zhipu",
        "name": "智谱 AI",
        "model_types": ["llm"],
        "base_url": "https://open.bigmodel.cn/api/paas/v4",
        "recommended_models": ["glm-4-plus", "glm-4-flash"],
    },
    {
        "id": "stability",
        "name": "Stability AI",
        "model_types": ["image"],
        "base_url": "https://api.stability.ai",
        "recommended_models": ["stable-image-core", "stable-diffusion-3"],
    },
    {
        "id": "wanxiang",
        "name": "通义万相",
        "model_types": ["image", "video"],
        "base_url": "https://dashscope.aliyuncs.com/api/v1",
        "recommended_models": ["wanx-v1", "wanx2.1-t2v-turbo"],
    },
    {
        "id": "jimeng",
        "name": "即梦",
        "model_types": ["image", "video"],
        "base_url": "https://visual.volcengineapi.com",
        "recommended_models": ["jimeng-image-v3", "jimeng-video-v3"],
    },
    {
        "id": "kling",
        "name": "可灵",
        "model_types": ["video"],
        "base_url": "https://api.klingai.com",
        "recommended_models": ["kling-v1-6", "kling-v2"],
    },
    {
        "id": "runway",
        "name": "Runway",
        "model_types": ["video"],
        "base_url": "https://api.runwayml.com",
        "recommended_models": ["gen3a_turbo", "gen4_turbo"],
    },
    {
        "id": "pika",
        "name": "Pika",
        "model_types": ["video"],
        "base_url": "https://api.pika.art",
        "recommended_models": ["pika-1.5"],
    },
    {
        "id": "luma",
        "name": "Luma",
        "model_types": ["video"],
        "base_url": "https://api.lumalabs.ai",
        "recommended_models": ["dream-machine"],
    },
]

DEFAULT_SCENARIOS = [
    {
        "id": "novel_creation",
        "name": "AI小说创作",
        "description": "用于大纲、角色、世界观、章节正文和润色。",
        "required_model_types": ["llm"],
        "optional_model_types": ["image"],
    },
    {
        "id": "novel_to_video",
        "name": "AI小说转视频创作",
        "description": "用于分镜脚本、提示词、分镜图和图生视频。",
        "required_model_types": ["llm", "image", "video"],
        "optional_model_types": [],
    },
]
